language: node_js
node_js:
- "node"
services: mongodb
before_install:
- npm update
install:
- npm install
env:
  - NODE_ENV=XXXX
  - PORT=3030
  - MONGODB_URI=mongodb://localhost:27017
  - MONGODB_DATABASE=test  
  - LENGTH_PASSWORD=8
  - JWT_SECRET_TOKEN=sdjnkfnjfsdqnjfdsnjkldsqfljknfdsjnfd
script:
- npm run test
