language: node_js
node_js:
- "node"
services: mongodb
before_install:
- npm update
install:
- npm install
env:
   MONGODB_URI=mongodb://localhost:27017
   MONGODB_DATABASE=test
   JWT_SECRET_TOKEN="faketoken"
  
script:
- npm run test
