version: "3"
services:
  app:
    container_name: express-mongo
    environment:
    - MONGODB_URI=mongodb://mongo:27017
    - MONGODB_DATABASE=metrics_docker
    - PORT=3030
    restart: always
    build: ./
    ports:
      - "3030:3030"
    volumes:
      - .:/app
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"